language: go
jobs:
  include:
    - go: "1.13"
      before_install:
        - go get github.com/mattn/goveralls
        - go get golang.org/x/lint/golint
    - go: "1.x"
      before_install:
        - go install github.com/mattn/goveralls@latest
        - go install golang.org/x/lint/golint@latest
script:
  - diff <(gofmt -s -d .) <(echo -n)
  - go vet ./...
  - golint ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
