language: go
go:
    - "1.12"
    - "1.x"
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/lint/golint
script:
    - diff <(gofmt -s -d .) <(echo -n)
    - go vet ./...
    - golint ./...
    - $HOME/gopath/bin/goveralls -service=travis-ci
