language: go
go:
    - 1.6
    - 1.7
    - 1.8
install:
    - go get github.com/hackedd/dicebot
    - go get github.com/hackedd/dicebot/cmd/dicebot
    - go get -v .
    - go get -v github.com/golang/lint/golint
script:
    - diff <(gofmt -s -d .) <(echo -n)
    - go vet -x ./...
    - golint ./...
    - go test ./...
